apiVersion: cis.f5.com/v1
kind: VirtualServer
metadata:
  name: argocd-vs
  namespace: argocd
  labels: { f5cr: "true" }
spec:
  host: argocd.sleepy-puppy.com
  virtualServerAddress: 10.50.0.10
  snat: "/Common/snat_k8s"
  tlsProfileName: argocd-tls
  pools:
    - path: /
      service: argocd-server
      servicePort: 80
