apiVersion: cis.f5.com/v1
kind: TLSProfile
metadata:
  name: keycloak-tls
  namespace: keycloak
  labels: { f5cr: "true" }
spec:
  tls:
    termination: edge
    reference: secret
    clientSSL: keycloak-tls          # <-- Kubernetes Secret name (type=tls)
  hosts:
    - keycloak.sleepy-puppy.com
---
apiVersion: cis.f5.com/v1
kind: VirtualServer
metadata:
  name: keycloak-vs
  namespace: keycloak
  labels: { f5cr: "true" }
spec:
  host: keycloak.sleepy-puppy.com
  virtualServerAddress: 10.50.0.12   # <-- your VIP
  snat: /Common/snat_k8s             # or "auto" if you don't have a SNAT pool
  tlsProfileName: keycloak-tls
  poolMemberType: nodeport           # <-- important with your NodePort service
  # Attach an iRule that injects X-Forwarded-* headers (create it on BIG-IP first)
  iRules:
    - /Common/kc_xfwd_headers
  pools:
    - path: /
      service: keycloak              # k8s Service name
      servicePort: 80                # matches your Service port (NodePort is mapped by CIS)

