apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak

configMapGenerator:
  - name: sleepy-theme
    files:
      - ../theme/theme.properties
      - ../theme/sleepy.css
      - ../theme/keycloak-logo.png

generatorOptions:
  disableNameSuffixHash: true
