grafana:
  ingress:
    enabled: false        # F5 publishes it; no NGINX ingress
  persistence:
    enabled: true
    existingClaim: grafana-nfs-pvc
  admin:
    existingSecret: kube-prom-grafana  # keys: admin-user, admin-password
  service:
    type: NodePort
    port: 80

prometheus:
  prometheusSpec:
    retention: 15d
defaultRules:
  create: false
