auth:
  existingSecret: keycloak-admin

extraEnvVars:
  - name: KC_PROXY
    value: "edge"
  - name: KC_HOSTNAME
    value: "keycloak.sleepy-puppy.com"
  - name: KC_HOSTNAME_STRICT
    value: "true"
  - name: KC_HTTP_RELATIVE_PATH
    value: "/"

service:
  type: NodePort
  ports:
    http: 80
  nodePorts:
    http: 32081

ingress:
  enabled: false

proxy: edge  # fine to keep; the env var also sets it in Keycloak

persistence:
  enabled: true
  size: 8Gi

postgresql:
  enabled: true
  auth:
    username: bn_keycloak
    database: bitnami_keycloak
    existingSecret: keycloak-postgresql   # keep using the same secret
  primary:
    persistence:
      enabled: true
      size: 8Gi
      storageClass:
