apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: richard@sleepy-puppy.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
    - dns01:
        webhook:
          groupName: acme.sleepy-puppy.com
          solverName: namecheap
          config:
            apiKeySecretRef:  { name: namecheap-api-key, key: apiKey }
            apiUserSecretRef: { name: namecheap-api-key, key: apiUser }

